name: actions-github-app-token
description: Obtain a GitHub App installation token
author: Ryan Anderson
inputs:
  GITHUB_APP_ID:
    description: your GitHub App ID
    required: true
  GITHUB_APP_PEM:
    description: base64 encoded string of your GitHub App PEM file (`cat key.pem | base64`)
    required: true
outputs:
  GITHUB_APP_TOKEN:
    description: installation access token for the GitHub App
branding:
  color: 'green'
  icon: 'user-check'
runs:
  using: 'node12'
  main: 'dist/index.js'
