name: 'build-test'

# rebuild any PRs and main branch changes
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # make sure build/ci work properly
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all

  # make sure the action works on a clean machine without building
  # test on all three platforms
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, macos-10.15, windows-2019 ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: app_token
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_APP_ID: ${{ secrets.RYANDY_BOT_APP_ID }}
          GITHUB_APP_PEM: ${{ secrets.RYANDY_BOT_APP_PEM }}
      - run: |
          echo "Masked output token: ${{ steps.app_token.outputs.GITHUB_APP_TOKEN }}"
